services:
  mafia_app:
    image: voiceofdarkness/mafia-game:latest
    container_name: mafia-game
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - web_gateway
    restart: always

networks:
  web_gateway:
    external: true
